# !!! IMPORTANT !!!
# This file is used only on developer's machines. Check README.md for instructions.
# Deployment configuration is in `.gitlab-ci.yml`.

services:
  sharer:
    # image: git.ia.surfsara.nl:5050/soil/rdx/backend:${DOCKER_IMAGE_TAG}
    image: rdx-backend:latest
    restart: "always"
    depends_on: [postgres]
    environment:
      RDX_APP_NAME: "sharer"
      LOG_LEVEL: "info"
      RDX_SMTP_HOST: ${RDX_SMTP_HOST}
      RDX_SMTP_PORT: ${RDX_SMTP_PORT}
      RDX_SMTP_USER: ${RDX_SMTP_USER}
      RDX_SMTP_PASSWORD: ${RDX_SMTP_PASSWORD}
      RDX_WEB_URL: ${RDX_WEB_URL}
      RDX_WEBDAV_PASSWORD: ${RDX_WEBDAV_PASSWORD}
      RDX_WEBDAV_USER: ${RDX_WEBDAV_USER}
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PORT: 5432
  librarian:
    # image: git.ia.surfsara.nl:5050/soil/rdx/backend:${DOCKER_IMAGE_TAG}
    image: rdx-backend:latest
    restart: "always"
    depends_on: [postgres]
    ports:
      - 8081:8081
    environment:
      RDX_APP_NAME: "librarian"
      LOG_LEVEL: "info"
      RDX_WEBDAV_PASSWORD: ${RDX_WEBDAV_PASSWORD}
      RDX_WEBDAV_USER: ${RDX_WEBDAV_USER}
      RDX_SMTP_HOST: ${RDX_SMTP_HOST}
      RDX_SMTP_PORT: ${RDX_SMTP_PORT}
      RDX_SMTP_USER: ${RDX_SMTP_USER}
      RDX_SMTP_PASSWORD: ${RDX_SMTP_PASSWORD}
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PORT: 5432

  frontend:
    image: rdx-frontend:latest
    restart: "always"
    depends_on: [librarian]
    ports:
      - 3000:3000
    environment:
      RDX_BACKEND_URL: http://librarian:8081
      RDX_PDF_HEADERS_PROXY_URL: ${RDX_PDF_HEADERS_PROXY_URL}
  postgres:
    image: postgres:13-alpine
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
