# !!! IMPORTANT !!!
# This file is used only on developer's machines. Check README.md for instructions.
# Deployment configuration is in `.gitlab-ci.yml`.

services:
  sharer:
    build: backend/v2/
    restart: "always"
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    env_file:
      - backend/v2/.env
    environment:
      APPLICATION: "sharer"
    # map mail server host to host.docker.internal IP so container can reach tunnel to mail server
    extra_hosts:
      - "mh.surfsara.nl:192.168.65.2"

  lab_runner:
    build: backend/v2/
    restart: "always"
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    env_file:
      - backend/v2/.env
    environment:
      APPLICATION: "lab_runner"
    # map mail server host to host.docker.internal IP so container can reach tunnel to mail server
    extra_hosts:
      - "mh.surfsara.nl:192.168.65.2"

  api:
    build: backend/v2/
    restart: "always"
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    ports:
      - 8000:8000
    env_file:
      - backend/v2/.env
    environment:
      APPLICATION: "api"
    # map mail server host to host.docker.internal IP so container can reach tunnel to mail server
    extra_hosts:
      - "mh.surfsara.nl:192.168.65.2"

  frontend:
    build: frontend
    restart: "always"
    depends_on: [api]
    ports:
      - 3000:3000
    environment:
      RDX_BACKEND_URL: http://api:8000

  postgres:
    image: postgres:14-alpine
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

  db-migrations:
    build: backend/v2/
    environment:
        APPLICATION: "database-migrations"
    env_file:
      - backend/v2/.env
    depends_on:
        postgres:
            condition: service_started
