---
- hosts: all
  vars_files:
    - vars/backend.yml

  tasks:
    # - name: Pull Docker images
    #   become: true
    #   tags: [docker]
    #   community.docker.docker_image: name="{{backend_image}}" source=pull

    - name: (Re-)start backend containers
      become: true
      tags: [docker]
      community.docker.docker_container:
        container_default_behavior: no_defaults
        pull: yes
        name: backend
        image: "{{ backend_image }}"
        recreate: yes
        restart_policy: "on-failure"
        env:
          # Tip: this list should be in sync with the env variables in all
          # `application.conf` and `reference.conf` files of the project.
          RDX_SMTP_USER: "{{ lookup('env', 'RDX_SMTP_USER') }}"
          RDX_SMTP_PASSWORD: "{{ lookup('env', 'RDX_SMTP_PASSWORD') }}"
          RDX_SMTP_HOST: "{{ lookup('env', 'RDX_SMTP_HOST') }}"
          RDX_SMTP_PORT: "{{ lookup('env', 'RDX_SMTP_PORT') }}"
          RDX_WEBDAV_USER: "{{ lookup('env', 'RDX_WEBDAV_USER') }}"
          RDX_WEBDAV_PASSWORD: "{{ lookup('env', 'RDX_WEBDAV_PASSWORD') }}"
