---
- hosts: all
  vars_files:
    - vars/backend.yml

  tasks:
    - name: Log into private registry and force re-authorization
      become: true
      community.general.docker_login:
        registry: "{{ docker_registry_url }}"
        username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
        reauthorize: yes
    - name: Update backend and DB containers
      become: true
      tags: [docker]
      community.docker.docker_compose:
        project_name: rdx
        remove_orphans: true
        definition:
          version: "2"
          services:
            postgres:
              image: postgres
              restart: "always"
              environment:
                POSTGRES_HOST_AUTH_METHOD: trust
            sharer:
              image: "{{ docker_registry_url }}/backend:{{ lookup('env', 'DOCKER_IMAGE_TAG') }}"
              restart: "always"
              depends_on: [postgres]
              environment:
                # Tip: this list should be in sync with the env variables in all
                # `application.conf` and `reference.conf` files of the project.
                RDX_SMTP_HOST: "{{ lookup('env', 'RDX_SMTP_HOST') }}"
                RDX_SMTP_PORT: "{{ lookup('env', 'RDX_SMTP_PORT') }}"
                RDX_SMTP_USER: "{{ lookup('env', 'RDX_SMTP_USER') }}"
                RDX_SMTP_PASSWORD: "{{ lookup('env', 'RDX_SMTP_PASSWORD') }}"
                RDX_WEB_URL: "{{ lookup('env', 'RDX_WEB_URL') }}"
                RDX_WEBDAV_USER: "{{ lookup('env', 'RDX_WEBDAV_USER') }}"
                RDX_WEBDAV_PASSWORD: "{{ lookup('env', 'RDX_WEBDAV_PASSWORD') }}"
                DB_HOST: "postgres"
                DB_NAME: "postgres"
                DB_USER: "postgres"
                DB_PORT: 5432
                LOG_LEVEL: "info"
                RDX_APP_NAME: "sharer"
            librarian:
              image: "{{ docker_registry_url }}/backend:{{ lookup('env', 'DOCKER_IMAGE_TAG') }}"
              restart: "always"
              depends_on: [postgres]
              ports:
                - 8081:8081
              environment:
                RDX_SMTP_HOST: "{{ lookup('env', 'RDX_SMTP_HOST') }}"
                RDX_SMTP_PORT: "{{ lookup('env', 'RDX_SMTP_PORT') }}"
                RDX_SMTP_USER: "{{ lookup('env', 'RDX_SMTP_USER') }}"
                RDX_SMTP_PASSWORD: "{{ lookup('env', 'RDX_SMTP_PASSWORD') }}"
                DB_HOST: "postgres"
                DB_NAME: "postgres"
                DB_USER: "postgres"
                DB_PORT: 5432
                RDX_APP_NAME: "librarian"
                LOG_LEVEL: "info"
                RDX_WEBDAV_USER: "{{ lookup('env', 'RDX_WEBDAV_USER') }}"
                RDX_WEBDAV_PASSWORD: "{{ lookup('env', 'RDX_WEBDAV_PASSWORD') }}"
            frontend:
              image: "{{ docker_registry_url }}/frontend:{{ lookup('env', 'DOCKER_IMAGE_TAG') }}"
              depends_on: [librarian]
              ports:
                - 3000:3000
              environment:
                RDX_BACKEND_URL: http://librarian:8081
    - name: Log out of docker registry
      become: true
      community.docker.docker_login:
        state: absent
