"""Add RdxJob model

Revision ID: 4e8b27257c38
Revises: 3c5a0c1a00fe
Create Date: 2023-02-21 14:20:23.818511

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e8b27257c38"
down_revision = "3c5a0c1a00fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_id_rdx_analyst_dataset", "rdx_analyst_dataset", ["id"]
    )
    op.create_table(
        "rdx_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rdx_analyst_dataset_link_id", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "script_location", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "workspace_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("results_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rdx_analyst_dataset_link_id"],
            ["rdx_analyst_dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rdx_job_status"), "rdx_job", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rdx_job_status"), table_name="rdx_job")
    op.drop_table("rdx_job")
    op.create_unique_constraint(
        "unique_id_rdx_analyst_dataset", "rdx_analyst_dataset", ["id"]
    )
    # ### end Alembic commands ###
