"""init

Revision ID: 54e25b6b4d5d
Revises: 
Create Date: 2022-10-13 14:39:50.350546

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "54e25b6b4d5d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rdx_dataset",
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column("doi", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("authors", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("files", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("conditions_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("condtions_share_id", sa.Integer(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rdx_dataset_condtions_share_id"),
        "rdx_dataset",
        ["condtions_share_id"],
        unique=False,
    )
    op.create_index(op.f("ix_rdx_dataset_doi"), "rdx_dataset", ["doi"], unique=False)
    op.create_index(
        op.f("ix_rdx_dataset_share_id"), "rdx_dataset", ["share_id"], unique=False
    )
    op.create_table(
        "rdx_share",
        sa.Column("share_id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uid_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "additional_info_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("permissions", sa.Integer(), nullable=False),
        sa.Column("rdx_dataset_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rdx_dataset_id"],
            ["rdx_dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rdx_share_share_id"), "rdx_share", ["share_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rdx_share_share_id"), table_name="rdx_share")
    op.drop_table("rdx_share")
    op.drop_index(op.f("ix_rdx_dataset_share_id"), table_name="rdx_dataset")
    op.drop_index(op.f("ix_rdx_dataset_doi"), table_name="rdx_dataset")
    op.drop_index(op.f("ix_rdx_dataset_condtions_share_id"), table_name="rdx_dataset")
    op.drop_table("rdx_dataset")
    # ### end Alembic commands ###
