"""Add tinker attributes to RdxJob

Revision ID: 56e67fbb166e
Revises: a66cb977019b
Create Date: 2023-07-10 10:55:36.153278

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "56e67fbb166e"
down_revision = "a66cb977019b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rdx_job",
        sa.Column("upload_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("rdx_job", sa.Column("upload_share_id", sa.Integer(), nullable=True))
    op.add_column(
        "rdx_job",
        sa.Column(
            "workspace_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "rdx_job",
        sa.Column(
            "workspace_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "rdx_job",
        sa.Column("workspace_ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column(
        "rdx_job", "script_location", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(
        op.f("ix_rdx_job_upload_share_id"), "rdx_job", ["upload_share_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rdx_job_upload_share_id"), table_name="rdx_job")
    op.alter_column(
        "rdx_job", "script_location", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("rdx_job", "workspace_ip")
    op.drop_column("rdx_job", "workspace_password")
    op.drop_column("rdx_job", "workspace_username")
    op.drop_column("rdx_job", "upload_share_id")
    op.drop_column("rdx_job", "upload_url")
    # ### end Alembic commands ###
