"""Add owncloud_private_link to RdxDataset

Revision ID: a66cb977019b
Revises: f32cf096fec0
Create Date: 2023-03-27 09:45:55.394629

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a66cb977019b'
down_revision = 'f32cf096fec0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rdx_dataset', sa.Column('owncloud_private_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rdx_dataset', 'owncloud_private_link')
    # ### end Alembic commands ###
